import { Platform } from "react-native";
import { reWriteUrl } from "../utils/utilFns";
 
export const baseURL=reWriteUrl(`http://localhost:7071/api/sequenceMakerAction`)

export const ACTION_TYPES = {
    VERSION_CHECK: 'VERSION_CHECK',
    APP_CONFIG: 'APP_CONFIG',
    GET_OTP: 'GET_OTP',
    CHECK_OTP: 'CHECK_OTP',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    GET_BALANCE: 'GET_BALANCE',
    ENTER_GAME: 'ENTER_GAME',
    LEAVE_GAME: 'LEAVE_GAME',
    SAVE_SUGGESTION: 'SAVE_SUGGESTION',
    ADD_BALANCE_INIT: 'ADD_BALANCE_INIT',
    ADD_BALANCE_FINALIZE: 'ADD_BALANCE_FINALIZE',
    WITHDRAW_BALANCE_INIT: 'WITHDRAW_BALANCE_INIT',
    GET_PAYMENT_HISTORY: 'GET_PAYMENT_HISTORY',
    ACT_TYP_ADD_VIRTUAL_BALANCE:'ACT_TYP_ADD_VIRTUAL_BALANCE'
  };
  